# -*- coding: utf-8 -*-
"""LAB4_1650700238_Manopakorn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ec7ueqf9jIK98-c_h6N44knW5FwRswuB
"""

#Order_Summary_Table
print("="*43)
print("|%13s %s %-13s|"%("***", "Order Summary", "***"))
print("-"*43)
print("")

#Summary
summary = eval(input("Enter Order summary : "))
if summary >= 3000 and summary <= 5000:
  discount = 60
elif summary >= 5000:
  discount = 120
else:
  discount = 0

#Destination_Table
print("-"*43)
print("| %15s %25s"%("Destination : ", "|"))
print("| %39s |"%("(BK) The Bangkok Metropolitan Region"))
print("| %36s %4s"%("(TH) For areas in other provinces", "|"))
print("-"*43)
print("")
destination = str(input("Enter destination       : ")).upper()

#BK
if destination == "BK":
  total_weight = eval(input("Enter total weight (KG) : "))
  if total_weight >= 1 and total_weight <= 5:
    shipping = 80
  elif total_weight >= 6 and total_weight <= 10:
    shipping = 150
  elif total_weight > 10:
    shipping = 200
  else :
    print("Invalid shipping" )
    
  #Weight_Table
  print("-"*43)
  print("| %9s%4s %7s%7s %6s%6s"%("Weight", "|", "BK", "|", "TH", "|"))
  print("-"*43)
  print("| %7s%6s %7s%7s %6s%6s"%("1-5", "|", "80", "|", "140", "|"))
  print("| %8s%5s %7s%7s %6s%6s"%("6-10", "|", "150", "|", "200", "|"))
  print("| %7s%6s %7s%7s %6s%6s"%("10+", "|", "200", "|", "250", "|"))
  print("-"*43)
  print("")

  order_total = summary + shipping - discount

  print("%s%8.2f"%("Order Summary : ", summary))
  print("%s%8.2f"%("Shipping      : ", shipping))
  print("%s%8.2f"%("Discount      : ",-discount))
  print("="*25)
  print("%s%8.2f"%("Order Total   : ",order_total))
  print("="*25)

#TH  
elif destination == "TH":
  total_weight = eval(input("Enter total weight (KG) : "))
  if total_weight >= 1 and total_weight <= 5:
    shipping = 140
  elif total_weight >= 6 and total_weight <= 10:
    shipping = 200
  elif total_weight > 10:
    shipping = 250
  else :
    print("Invalid shipping" )  

  #Weight_Table
  print("-"*43)
  print("| %9s%4s %7s%7s %6s%6s"%("Weight", "|", "BK", "|", "TH", "|"))
  print("-"*43)
  print("| %7s%6s %7s%7s %6s%6s"%("1-5", "|", "80", "|", "140", "|"))
  print("| %8s%5s %7s%7s %6s%6s"%("6-10", "|", "150", "|", "200", "|"))
  print("| %7s%6s %7s%7s %6s%6s"%("10+", "|", "200", "|", "250", "|"))
  print("-"*43)
  print("")

  order_total = summary + shipping - discount

  print("%s%8.2f"%("Order Summary : ", summary))
  print("%s%8.2f"%("Shipping      : ", shipping))
  print("%s%8.2f"%("Discount      : ",-discount))
  print("="*25)
  print("%s%8.2f"%("Order Total   : ",order_total))
  print("="*25)

#Error
else:
  print("Invalid destination code! Please try again.")